title: DirtCamAdventure (DCA)
description: Technical dirt bike gear and Hartley Vale trail guides.
theme: minima

# URL Settings
url: "https://github.io"
baseurl: "/dirtcamadventure"

# This makes your menu at the top automatically
header_pages:
  - index.md
  - giveaway.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
